setup: set range for sympy versions
Ensure that sympy <= 1.11, since sympy 1.12 will cause
the GenSympyTest.test_estimator test to fail with
error "ValueError: duplicate symbols given"
for python 3.9.0 on windows 10 64-bit.